blueprint:
  homeassistant:
    min_version: 2024.10.0
  author: yarafie
  domain: automation
  name: z2m - IKEA STYRBAR remote control (E2001/E2002) - Multi-device
  description: >
    This blueprint is for the IKEA STYRBAR square, 4-button remote when used with zigbee2mqtt.
    Supports multiple remotes, each triggering the same set of actions.
  source_url: https://github.com/yarafie/HA-BluePrints/blob/main/z2m-IKEA-styrbar_E2001_E2002.yaml
#
# Define UI and default values
  input:
    remote_devices:
      name: Remotes
      description: Select IKEA STYRBAR remotes to use
      default: []
      selector:
        target:
          entity:
            integration: mqtt
            manufacturer: IKEA
            model: STYRBAR remote control
    button_on:
      name: Brightness up button - short press
      description: Action to run when SHORT press on brightness UP button
      default: []
      selector:
        action: {}
    button_off:
      name: Brightness down button - short press
      description: Action to run when SHORT press on brightness DOWN button
      default: []
      selector:
        action: {}
    button_brightness_move_up:
      name: Brightness up button - long press
      description: Action to run when LONG press on brightness UP button
      default: []
      selector:
        action: {}
    button_brightness_move_down:
      name: Brightness down button - long press
      description: Action to run when LONG press on brightness DOWN button
      default: []
      selector:
        action: {}
    button_brightness_stop:
      name: Brightness stop button - long release press
      description: Action to run when LONG press on brightness (up or down) is released
      default: []
      selector:
        action: {}
    button_left_click:
      name: Left button - short press
      description: Action to run when SHORT press on LEFT arrow button
      default: []
      selector:
        action: {}
    button_left_hold:
      name: Left button - hold
      description: Action to run when HOLD press on LEFT arrow button
      default: []
      selector:
        action: {}
    button_left_release:
      name: Left button - release
      description: Action to run when RELEASE press on LEFT arrow button
      default: []
      selector:
        action: {}
    button_right_click:
      name: Right button - short press
      description: Action to run when SHORT press on RIGHT arrow button
      default: []
      selector:
        action: {}
    button_right_hold:
      name: Right button - hold
      description: Action to run when HOLD press on RIGHT button
      default: []
      selector:
        action: {}
    button_right_release:
      name: Right button - release
      description: Action to run when RELEASE press on RIGHT arrow button
      default: []
      selector:
        action: {}
#
# Define mode for automation
mode: restart
max_exceeded: silent
#
# Define Triggers for automation
trigger:
  - platform: device
    device_id: !input remote_devices
    type: action
    subtype: 'on'
    id: press-top-z2m-e2001
  - platform: device
    device_id: !input remote_devices
    type: action
    subtype: 'off'
    id: press-bottom-z2m-e2001
  - platform: device
    device_id: !input remote_devices
    type: action
    subtype: brightness_move_up
    id: hold-top-z2m-e2001
  - platform: device
    device_id: !input remote_devices
    type: action
    subtype: brightness_move_down
    id: hold-bottom-z2m-e2001
  - platform: device
    device_id: !input remote_devices
    type: action
    subtype: brightness_stop
    id: release-z2m-e2001
  - platform: device
    device_id: !input remote_devices
    type: action
    subtype: arrow_left_click
    id: press-left-z2m-e2001
  - platform: device
    device_id: !input remote_devices
    type: action
    subtype: arrow_left_hold
    id: hold-left-z2m-e2001
  - platform: device
    device_id: !input remote_devices
    type: action
    subtype: arrow_left_release
    id: release-left-z2m-e2001
  - platform: device
    device_id: !input remote_devices
    type: action
    subtype: arrow_right_click
    id: press-right-z2m-e2001
  - platform: device
    device_id: !input remote_devices
    type: action
    subtype: arrow_right_hold
    id: hold-right-z2m-e2001
  - platform: device
    device_id: !input remote_devices
    type: action
    subtype: arrow_right_release
    id: release-right-z2m-e2001
#
# Define actions
action:
  - choose:
      - conditions:
          - condition: trigger
            id: press-top-z2m-e2001
        sequence: !input button_on
      - conditions:
          - condition: trigger
            id: press-bottom-z2m-e2001
        sequence: !input button_off
      - conditions:
          - condition: trigger
            id: hold-top-z2m-e2001
        sequence: !input button_brightness_move_up
      - conditions:
          - condition: trigger
            id: hold-bottom-z2m-e2001
        sequence: !input button_brightness_move_down
      - conditions:
          - condition: trigger
            id: release-z2m-e2001
        sequence: !input button_brightness_stop
      - conditions:
          - condition: trigger
            id: press-left-z2m-e2001
        sequence: !input button_left_click
      - conditions:
          - condition: trigger
            id: hold-left-z2m-e2001
        sequence: !input button_left_hold
      - conditions:
          - condition: trigger
            id: release-left-z2m-e2001
        sequence: !input button_left_release
      - conditions:
          - condition: trigger
            id: press-right-z2m-e2001
        sequence: !input button_right_click
      - conditions:
          - condition: trigger
            id: hold-right-z2m-e2001
        sequence: !input button_right_hold
      - conditions:
          - condition: trigger
            id: release-right-z2m-e2001
        sequence: !input button_right_release
