# ==========================================================
# -------------------------------------------
# IKEA STYRBAR remote control (E2001/E2002)
# -------------------------------------------
#  Button -> action mapping
#  ---------------------------------------------------------
# | Icon                   | Action  | Exposed Action       |
# |---------------------------------------------------------|
# | Light large ( top )    | push    | on                   |
# | Light large ( top )    | hold    | brightness_move_up   |
# | Light large ( top )    | release | brightness_stop      |
# |---------------------------------------------------------|
# | Light small ( bottom ) | push    | off                  |
# | Light small ( bottom ) | hold    | brightness_move_down |
# | Light small ( bottom ) | release | brightness_stop      |
# |---------------------------------------------------------|
# | Arrow left             | push    | arrow_left_click     |
# | Arrow left             | hold    | arrow_left_hold      |
# | Arrow left             | release | arrow_left_release   |
# |---------------------------------------------------------|
# | Arrow right            | push    | arrow_right_click    |
# | Arrow right            | hold    | arrow_right_hold     |
# | Arrow right            | release | arrow_right_release  |
# |---------------------------------------------------------|
# | For the arrow buttons it seems that the hold/move       | 
# | action  takes a bit longer to be send.                  |
#  ---------------------------------------------------------
# Action (enum)
# The possible values are:
#  1. on
#  2. off
#  3. brightness_move_up
#  4. brightness_move_down
#  5. brightness_stop
#  6. arrow_left_click
#  7. arrow_left_hold
#  8. arrow_left_release
#  9. arrow_right_click
# 10. arrow_right_hold
# 11. arrow_right_release
# ==========================================================
blueprint:
  name: z2m - IKEA STYRBAR remote control (E2001/E2002) - Multi-device
  description: >
    This blueprint is for the IKEA STYRBAR square, 4-button remote when used with zigbee2mqtt.
    Supports multiple remotes, each triggering the same set of actions. Inputs left blank will do nothing.
  domain: automation
  input:
    remote_devices:
      name: Remotes
      description: Select IKEA STYRBAR remotes to use
      selector:
        device:
          integration: mqtt
          manufacturer: IKEA
          model: STYRBAR remote control
          multiple: true
    button_on:
      name: Brightness up button - short press
      description: Action to run when SHORT press on brightness UP button
      default: []
      selector:
        action: {}
    button_off:
      name: Brightness down button - short press
      description: Action to run when SHORT press on brightness DOWN button
      default: []
      selector:
        action: {}
    button_brightness_move_up:
      name: Brightness up button - long press
      description: Action to run when LONG press on brightness UP button
      default: []
      selector:
        action: {}
    button_brightness_move_down:
      name: Brightness down button - long press
      description: Action to run when LONG press on brightness DOWN button
      default: []
      selector:
        action: {}
    button_brightness_stop:
      name: Brightness stop button - release
      description: Action to run when LONG press (up or down) is released
      default: []
      selector:
        action: {}
    button_left_click:
      name: Left button - short press
      description: Action to run when SHORT press on LEFT arrow button
      default: []
      selector:
        action: {}
    button_left_hold:
      name: Left button - hold
      description: Action to run when HOLD press on LEFT arrow button
      default: []
      selector:
        action: {}
    button_left_release:
      name: Left button - release
      description: Action to run when RELEASE press on LEFT arrow button
      default: []
      selector:
        action: {}
    button_right_click:
      name: Right button - short press
      description: Action to run when SHORT press on RIGHT arrow button
      default: []
      selector:
        action: {}
    button_right_hold:
      name: Right button - hold
      description: Action to run when HOLD press on RIGHT arrow button
      default: []
      selector:
        action: {}
    button_right_release:
      name: Right button - release
      description: Action to run when RELEASE press on RIGHT arrow button
      default: []
      selector:
        action: {}

trigger:
  - platform: mqtt
    topic: zigbee2mqtt/+
    id: any_action

condition:
  - condition: template
    value_template: >
      {{ trigger.payload_json.action in [
          'on', 'off', 'brightness_move_up', 'brightness_move_down',
          'brightness_stop', 'arrow_left_click', 'arrow_left_hold',
          'arrow_left_release', 'arrow_right_click', 'arrow_right_hold',
          'arrow_right_release'
      ] and trigger.topic.split('/')[-1] in expand('!input remote_devices') | map(attribute='entity_id') }}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'on' }}"
        sequence: !input button_on
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'off' }}"
        sequence: !input button_off
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'brightness_move_up' }}"
        sequence: !input button_brightness_move_up
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'brightness_move_down' }}"
        sequence: !input button_brightness_move_down
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'brightness_stop' }}"
        sequence: !input button_brightness_stop
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'arrow_left_click' }}"
        sequence: !input button_left_click
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'arrow_left_hold' }}"
        sequence: !input button_left_hold
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'arrow_left_release' }}"
        sequence: !input button_left_release
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'arrow_right_click' }}"
        sequence: !input button_right_click
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'arrow_right_hold' }}"
        sequence: !input button_right_hold
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'arrow_right_release' }}"
        sequence: !input button_right_release
    default: []
