# ==========================================================
# -------------------------------------------
# IKEA STYRBAR remote control (E2001/E2002)
# -------------------------------------------
#  Button -> action mapping
#  ---------------------------------------------------------
# | Icon                   | Action  | Exposed Action       |
# |---------------------------------------------------------|
# | Light large ( top )    | push    | on                   |
# | Light large ( top )    | hold    | brightness_move_up   |
# | Light large ( top )    | release | brightness_stop      |
# |---------------------------------------------------------|
# | Light small ( bottom ) | push    | off                  |
# | Light small ( bottom ) | hold    | brightness_move_down |
# | Light small ( bottom ) | release | brightness_stop      |
# |---------------------------------------------------------|
# | Arrow left             | push    | arrow_left_click     |
# | Arrow left             | hold    | arrow_left_hold      |
# | Arrow left             | release | arrow_left_release   |
# |---------------------------------------------------------|
# | Arrow right            | push    | arrow_right_click    |
# | Arrow right            | hold    | arrow_right_hold     |
# | Arrow right            | release | arrow_right_release  |
# |---------------------------------------------------------|
# | For the arrow buttons it seems that the hold/move       | 
# | action  takes a bit longer to be send.                  |
#  ---------------------------------------------------------
# Action (enum)
# The possible values are:
#  1. on
#  2. off
#  3. brightness_move_up
#  4. brightness_move_down
#  5. brightness_stop
#  6. arrow_left_click
#  7. arrow_left_hold
#  8. arrow_left_release
#  9. arrow_right_click
# 10. arrow_right_hold
# 11. arrow_right_release
# ==========================================================
blueprint:
  name: z2m - IKEA STYRBAR remote control (E2001/E2002)
  description: >
    This blueprint is for the IKEA STYRBAR square, 4-button remote when used with zigbee2mqtt.
    You can trigger actions from multiple remotes by defining their `device_id`s.

  domain: automation
  input:
    remote_devices:
      name: Remotes
      description: List of IKEA STYRBAR remotes to use
      selector:
        device:
          integration: mqtt
          manufacturer: IKEA
          model: STYRBAR remote control
          multiple: true
    button_on:
      name: Brightness up button - short press
      description: Action to run when SHORT press on brightness UP button
      default: []
      selector:
        action: {}
    button_off:
      name: Brightness down button - short press
      description: Action to run when SHORT press on brightness DOWN button
      default: []
      selector:
        action: {}
    button_brightness_move_up:
      name: Brightness up button - long press
      description: Action to run when LONG press on brightness UP button
      default: []
      selector:
        action: {}
    button_brightness_move_down:
      name: Brightness down button - long press
      description: Action to run when LONG press on brightness DOWN button
      default: []
      selector:
        action: {}
    button_brightness_stop:
      name: Brightness stop button - release
      description: Action to run when LONG press (up or down) is released
      default: []
      selector:
        action: {}
    button_left_click:
      name: Left button - short press
      description: Action to run when SHORT press on LEFT arrow button
      default: []
      selector:
        action: {}
    button_left_hold:
      name: Left button - hold
      description: Action to run when HOLD press on LEFT arrow button
      default: []
      selector:
        action: {}
    button_left_release:
      name: Left button - release
      description: Action to run when RELEASE press on LEFT arrow button
      default: []
      selector:
        action: {}
    button_right_click:
      name: Right button - short press
      description: Action to run when SHORT press on RIGHT arrow button
      default: []
      selector:
        action: {}
    button_right_hold:
      name: Right button - hold
      description: Action to run when HOLD press on RIGHT arrow button
      default: []
      selector:
        action: {}
    button_right_release:
      name: Right button - release
      description: Action to run when RELEASE press on RIGHT arrow button
      default: []
      selector:
        action: {}

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      command: "off"
    id: press-top-z2m-e2001
  - platform: event
    event_type: zha_event
    event_data:
      command: "on"
    id: press-bottom-z2m-e2001
  - platform: event
    event_type: zha_event
    event_data:
      command: "brightness_move_up"
    id: hold-top-z2m-e2001
  - platform: event
    event_type: zha_event
    event_data:
      command: "brightness_move_down"
    id: hold-bottom-z2m-e2001
  - platform: event
    event_type: zha_event
    event_data:
      command: "brightness_stop"
    id: release-z2m-e2001

condition:
  - condition: template
    value_template: >
      {{ trigger.event.data.device_id in
        states('input_text.remote_devices').split(',') }}

action:
  - choose:
      - conditions:
          - condition: trigger
            id: press-top-z2m-e2001
        sequence: !input button_on
      - conditions:
          - condition: trigger
            id: press-bottom-z2m-e2001
        sequence: !input button_off
      - conditions:
          - condition: trigger
            id: hold-top-z2m-e2001
        sequence: !input button_brightness_move_up
      - conditions:
          - condition: trigger
            id: hold-bottom-z2m-e2001
        sequence: !input button_brightness_move_down
      - conditions:
          - condition: trigger
            id: release-z2m-e2001
        sequence: !input button_brightness_stop
      - conditions:
          - condition: trigger
            id: press-left-z2m-e2001
        sequence: !input button_left_click
      - conditions:
          - condition: trigger
            id: hold-left-z2m-e2001
        sequence: !input button_left_hold
      - conditions:
          - condition: trigger
            id: release-left-z2m-e2001
        sequence: !input button_left_release
      - conditions:
          - condition: trigger
            id: press-right-z2m-e2001
        sequence: !input button_right_click
      - conditions:
          - condition: trigger
            id: hold-right-z2m-e2001
        sequence: !input button_right_hold
      - conditions:
          - condition: trigger
            id: release-right-z2m-e2001
        sequence: !input button_right_release
    default: []
