blueprint:
  name: z2m - IKEA STYRBAR remote control (E2001/E2002) - Multi-device
  description: >
    This blueprint is for the IKEA STYRBAR square, 4-button remote when used with zigbee2mqtt.
    Supports multiple remotes, each triggering the same set of actions.
  domain: automation
  input:
    remote_devices:
      name: Remotes
      description: Select IKEA STYRBAR remotes to use
      selector:
        target:
          entity:
            integration: mqtt
            manufacturer: IKEA
            model: STYRBAR remote control
    button_on:
      name: Brightness up button - short press
      selector:
        action: {}
    button_off:
      name: Brightness down button - short press
      selector:
        action: {}
    button_brightness_move_up:
      name: Brightness up button - long press
      selector:
        action: {}
    button_brightness_move_down:
      name: Brightness down button - long press
      selector:
        action: {}
    button_brightness_stop:
      name: Brightness stop button - release
      selector:
        action: {}
    button_left_click:
      name: Left button - short press
      selector:
        action: {}
    button_left_hold:
      name: Left button - hold
      selector:
        action: {}
    button_left_release:
      name: Left button - release
      selector:
        action: {}
    button_right_click:
      name: Right button - short press
      selector:
        action: {}
    button_right_hold:
      name: Right button - hold
      selector:
        action: {}
    button_right_release:
      name: Right button - release
      selector:
        action: {}

trigger:
  - platform: mqtt
    topic: zigbee2mqtt/+
    id: any_action

condition:
  - condition: template
    value_template: >
      {{ trigger.payload_json.action in [
          'on', 'off', 'brightness_move_up', 'brightness_move_down',
          'brightness_stop', 'arrow_left_click', 'arrow_left_hold',
          'arrow_left_release', 'arrow_right_click', 'arrow_right_hold',
          'arrow_right_release'
      ] and trigger.topic.split('/')[-1] in expand('!input remote_devices') | map(attribute='entity_id') }}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'on' }}"
        sequence: !input button_on
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'off' }}"
        sequence: !input button_off
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'brightness_move_up' }}"
        sequence: !input button_brightness_move_up
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'brightness_move_down' }}"
        sequence: !input button_brightness_move_down
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'brightness_stop' }}"
        sequence: !input button_brightness_stop
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'arrow_left_click' }}"
        sequence: !input button_left_click
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'arrow_left_hold' }}"
        sequence: !input button_left_hold
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'arrow_left_release' }}"
        sequence: !input button_left_release
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'arrow_right_click' }}"
        sequence: !input button_right_click
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'arrow_right_hold' }}"
        sequence: !input button_right_hold
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'arrow_right_release' }}"
        sequence: !input button_right_release
