blueprint:
  homeassistant:
    min_version: 2024.10.0
  author: yarafie
  domain: automation
  name: Zigbee2MQTT - Ikea RODRET dimmer (E2201)
  description: "This blueprint is for the IKEA RODRET dimmer, 2-button remote when used with zigbee2mqtt.
  It is for general use so all buttons can be connected to any action of your choice"
  source_url: https://github.com/yarafie/HA-BluePrints/blob/main/Zigbee2MQTT-Ikea-RODRET-dimmer-E2201.yaml
  input:
    controller:
      name: Zigbee2MQTT IKEA Remote Name
      description: IKEA RODRET dimmer to use - Exact Friendly name as shown in Zigbee2MQTT
      default: ''
      selector:
        device:
          filter:
          - integration: mqtt
            manufacturer: IKEA
            model: RODRET wireless dimmer/power switch (E2201)
          multiple: false
    base_topic:
      name: (Zigbee2MQTT) Base mqtt topic
      description: The base topic as configured in z2m (keep unless Z2M non-default configuation)
      default: zigbee2mqtt
    button_on:
      name: On button - short press
      description: Action to run when SHORT press on On button
      default: []
      selector:
        action: {}
    button_off:
      name: Off button - short press
      description: Action to run when SHORT press on Off button
      default: []
      selector:
        action: {}
    button_on_long_press:
      name: On button - long press
      description: Action to run when LONG press on On button
      default: []
      selector:
        action: {}
    button_off_long_press:
      name: Off button - long press
      description: Action to run when LONG press on Off button
      default: []
      selector:
        action: {}
    button_long_press_stop:
      name: On/Off stopped after long press release 
      description: Action to run when LONG press on (On or Off) is released
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent
trigger_variables:
  base_topic: !input base_topic
  controller: !input controller
trigger:
- platform: mqtt
  topic: '{{ base_topic ~ ''/'' ~ controller ~ ''/action'' }}'
condition:
  - condition: template
    value_template: '{{ trigger.payload_json.action }}'
action:
- variables:
    command: '{{ trigger.payload_json.action }}'
- choose:
  - conditions:
    - '{{ command == "on" }}'
    sequence: !input button_on
  - conditions:
    - '{{ command == "off" }}'
    sequence: !input button_off
  - conditions:
    - '{{ command == "brightness_move_up" }}'
    sequence: !input button_on_long_press
  - conditions:
    - '{{ command == "brightness_move_down" }}'
    sequence: !input button_off_long_press
  - conditions:
    - '{{ command == "brightness_stop" }}'
    sequence: !input button_long_press_stop
